version: '3.4'
services:
  user-api:
    build: ./users
    ports:
      - "5001:5001"
    env_file:
      - ./users/.env
  user-task-api:
    build: ./userTasks
    ports:
      - "5003:5003"
    env_file:
      - ./userTasks/.env

    